"""update profile

Revision ID: aa54090d635f
Revises: ca2c3df4c621
Create Date: 2026-08-09 00:53:52.991058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa54090d635f'
down_revision: Union[str, Sequence[str], None] = 'ca2c3df4c621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'name')
    # ### end Alembic commands ###
