"""add is_admin to post

Revision ID: e08d816deaa1
Revises: aa54090d635f
Create Date: 2026-09-21 13:26:43.896688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08d816deaa1'
down_revision: Union[str, Sequence[str], None] = 'aa54090d635f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_admin')
    # ### end Alembic commands ###
