"""update db config

Revision ID: ea6665bc6bc6
Revises: ca46a9388f6f
Create Date: 2026-07-21 19:44:47.871899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea6665bc6bc6'
down_revision: Union[str, Sequence[str], None] = 'ca46a9388f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'created_at')
    op.drop_column('batch', 'created_at')
    op.drop_column('post', 'created_at')
    op.drop_column('profile', 'created_at')
    op.drop_column('student_master', 'created_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('student_master', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('profile', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('batch', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('admin', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
